# -*- coding: utf-8 -*-
"""MAJOR PROJECT - 01 (SUPPLY CHAIN OPTIMIZATION).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oqwfOY1CfFgmFEI3ABilPTRqJmMbnKTr

# **SUPPLY CHAIN OPTIMIZATION**

**Install Required Libraries**
"""

!pip install xgboost streamlit scikit-learn --quiet

"""**Import Libraries**"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from xgboost import XGBRegressor

"""**Uploading Dataset**"""

from google.colab import files
uploaded = files.upload()

"""**Load and Preprocess Data**"""

def load_and_clean_data(file):
    df = pd.read_csv('/content/supply_chain_data (1).csv')
    df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")

    # Convert date fields if present
    if 'lead_time' in df.columns:
        df['lead_time'] = pd.to_numeric(df['lead_time'], errors='coerce')
    if 'manufacturing_lead_time' in df.columns:
        df['manufacturing_lead_time'] = pd.to_numeric(df['manufacturing_lead_time'], errors='coerce')

    # Fill or drop missing values
    df.dropna(subset=['product_type', 'sku', 'price', 'number_of_products_sold', 'revenue_generated'], inplace=True)
    return df

df = load_and_clean_data('supply_chain_data.csv')
df.head()

"""**Exploratory Data Analysis (EDA)**"""

import matplotlib.pyplot as plt
import seaborn as sns

# Revenue by product type
plt.figure(figsize=(12,6))
sns.barplot(data=df, x='product_type', y='revenue_generated', estimator=sum, ci=None)
plt.xticks(rotation=45)
plt.title('Total Revenue by Product Type')
plt.show()

# Stock level vs defect rate
plt.figure(figsize=(10,6))
sns.scatterplot(x='stock_levels', y='defect_rates', hue='product_type', data=df)
plt.title('Stock Levels vs Defect Rates')
plt.show()

"""**Supplier Clustering**"""

from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans

def supplier_clustering(df):
    # Map inspection results to numeric
    if 'inspection_results' in df.columns:
        df['inspection_score'] = df['inspection_results'].map({
            'Pass': 1,
            'Fail': 0,
            'Pending': 0.5
        })

    # Group by supplier and calculate relevant numeric means
    cluster_df = df.groupby('supplier_name')[[
        'lead_time', 'manufacturing_costs', 'defect_rates', 'inspection_score'
    ]].mean().dropna()

    scaler = StandardScaler()
    scaled = scaler.fit_transform(cluster_df)

    km = KMeans(n_clusters=4, random_state=42)
    cluster_df['cluster'] = km.fit_predict(scaled)

    return cluster_df

supplier_clusters = supplier_clustering(df)
supplier_clusters.head()

"""**Demand Forecasting Using XGBoost**"""

from sklearn.model_selection import train_test_split
from xgboost import XGBRegressor

def forecast_demand(df):
    features = df[['price', 'stock_levels', 'manufacturing_costs']].copy()
    target = df['number_of_products_sold']

    features = features.dropna()
    target = target[features.index]

    X_train, X_test, y_train, y_test = train_test_split(features, target, test_size=0.2, random_state=42)

    model = XGBRegressor()
    model.fit(X_train, y_train)
    score = model.score(X_test, y_test)
    print(f"Demand Forecasting Accuracy (R²): {score*100:.2f}%")
    return model

demand_model = forecast_demand(df)

"""**EOQ & Reorder Point Calculation**"""

import numpy as np

def calculate_eoq(demand_rate, ordering_cost, holding_cost):
    return np.sqrt((2 * demand_rate * ordering_cost) / holding_cost)

def reorder_point(daily_demand, lead_time):
    return daily_demand * lead_time

# Use values from dataset if available, else defaults
annual_demand = df['number_of_products_sold'].sum()
ordering_cost = df['shipping_costs'].mean() if 'shipping_costs' in df else 50
holding_cost = df['price'].mean() * 0.1

eoq = calculate_eoq(annual_demand, ordering_cost, holding_cost)
rop = reorder_point(daily_demand=annual_demand/365, lead_time=7)

print("EOQ:", round(eoq, 2))
print("Reorder Point:", round(rop, 2))

"""**Lead Time Analysis**"""

def lead_time_by_supplier(df):
    return df.groupby('supplier_name')['lead_time'].mean().sort_values()

lead_time_summary = lead_time_by_supplier(df)
lead_time_summary.head()

"""**Summary of Results**"""

print("Top 5 Fastest Suppliers (by average lead time):")
print(lead_time_summary.head())

print("\nSupplier Clusters Distribution:")
print(supplier_clusters['cluster'].value_counts())